function aboutECGtool()

msgbox({'EKGtool version 3.0' ...
'University of Tampere'...
'Human Information Processing Laboratory' ...
'School of Social Sciences and Humanities' ...
'' ...
'' ...
['EKGtool is a program designed to detect R-peaks from EKG-signal, and to ' ...
'calculate event related heartrates and RR-series metrics. You can load EKG-data ' ...
'from .dat-file produced by Neuroscan or Analyzer and event-data from .ev2-file, ' ...
'vmrk-file or handmade text-file with colums of event type and datapoint corresponding to the event onset. '...
'After that you can detect and edit R-peaks by clikcking the buttons or a specific spot on the EKG-curve. ' ...
'By clicking "HeartRate analysis"-button you can calculate heartrates and save them. By clicking '...
'"rr-analysis"-button you can calculate various metrics over the RR-series.' ] ...
'' ...
'' ...
'Please refer to documentation such as "EKGtool_dokumentation.pdf" enclosed with this program for more information. ' ...
'' ...
'29.7.2011 Tampere, Finland'}, 'Ekgtool 3.0');